module.exports = {
    REJECTED_SUCCESS: 'Rejetced Successfully',
    REJECTED_FAILURE: 'Unable to reject at this moment',
    REQUEST_SENT_SUCCESS: 'Request sent successfully',
    REQUEST_SENT_FAILURE: 'Unable to send request',
    REQUEST_ALREADY_SENT: 'Request already sent',
    DATA_FOUND_SUCCESS: 'Data found successfully',
    DATA_NOT_FOUND: 'No data found',
    CONNECTED_SUCCESS: 'Connected Successfully',
    CONNECTED_FAILURE: 'Unable to connect at this moment',
    USER_DATA_FOUND: 'Data found Success',
    SUPER_LIKED_SUCCESS: 'Super liked successfully',
    SUPER_LIKED_FAILURE: 'Unable to super like at this moment',
    UNDO_SUCCESS: 'Undo successfully',
    UNDO_FAILURE: 'Unable to undo at this moment',
    NOTHING_TO_UNDO: 'Nothing to undo',
    CONNECTIONS_FOUND_SUCCESS: 'Connection found successfully',
    CONNECTIONS_FOUND_FAILURE: 'No connection found',
    CONNECTION_REMOVED_SUCCESS: 'Conenction removed successfully',
    CONNECTION_REMOVED_FAILURE: 'Unable to remove connection. Try Again!',
    REQUEST_REVOKED_SUCCESS: 'Request revoked successfully!',
    REQUEST_REVOKED_FAILURE: 'Unable to revoke request. Try Again!',
    DELETED_SUCCESS: 'Deleted Successfully',
    DELETED_FAILURE: 'Unable to delete . Try again',
}