module.exports = {
    DATA_FOUND_SUCCESS: 'Data found successfully',
    DATA_NOT_FOUND: 'Data not found',
    USER_DOESNT_EXIST: 'User not exist',
    MEDIA_NOT_SELECTED: 'Image Not selected',
    DATA_ADDED_SUCCESS: 'Data Added Successfully',
    DATA_ADDED_FAILURE: 'Unable to add data at this moment',
    INTEREST_UPDATE_SUCCESSS: 'Interest Updated Successfully',
    INTEREST_UPDATE_FAILURE: 'Unable to update Interest',
    INVALID_ADMIN: 'Invalid Admin',
    STATUS_UPDATE_SUCCESS: 'Status updated successfully',
    STATUS_UPDATE_FAILURE: 'Unable to update status at this moment',
    DATA_UPDATE_SUCCESS: 'Updated Successfully',
    DATA_UPDATE_FAILURE: 'Unable to udpate at this moment',
    ICON_NOT_SELECTED: 'Icon not selected',
    IMAGE_NOT_SELECTED: 'Image not selected',
    CONNECTION_ADDED_SUCCESS: 'Connection Type added successfully',
    CONNECTION_ADDED_FAILURE: 'Unable to add connection type at this moment',
    CONNECTION_TYPE_UPDATE_SUCCESS: 'Connection Type Updated Successfully',
    CONNECTION_TYPE_UPDATE_FAILURE: 'Unable to updated connection type at this moment',
    CONNECTION_IMAGE_REMOVED_SUCCESS: 'Connection Image Removed Successfully',
    CONNECTION_IMAGE_REMOVED_FAILURE: 'Unable to remove image at this moment',
    CONNECTION_IMAGE_ADD_SUCCESS: 'Connection image added successfully',
    CONNECTION_IMAGE_ADD_FAILURE: 'Unable to added image at this moment',
    CONNECTION_IMAGE_UPDATE_SUCCESS: 'Connection image updated successfully ',
    CONNECTION_IMAGE_UPDATE_FAILURE: 'Unable to update image at this moment',
    CONNECTION_DELETE_SUCCESS: 'Connection Type deleted successfully',
    CONNECTION_DELETE_FAILURE: 'unable to delete connection type at this moment',
    UPDATE_SUCCESS: 'Updated successfully',
    UPDATE_FAILURE: 'Unable to update  at this moment',
    ORDER_UPDATE_SUCCESS: 'Order update successfully',
}