module.exports = {
    PHONE_ALREADY_EXIST: 'Phone Number Already Registered',
    USER_DOESNT_EXIST: 'User doesnot exist',
    OTP_SENT_SUCCESS: 'OTP sent successfully',
    OTP_SENT_FAILURE: 'Unable to send OTP at this moment!',
    UNABLE_TO_UPDATE_OTP: 'Unable to update OTP on DB!',
    OTP_VERIFIED_SUCCESS: 'OTP verified successfully',
    OTP_VERIFIED_FAILURE: 'Invalid OTP',
    PROFILE_UPDATE_SUCCESS: 'Profile Updated Successfully',
    PROFILE_UPDATE_FAILURE: 'Unable to update profile details',
    USER_DATA_FOUND: 'User Data Found',
    DATA_NOT_FOUND: 'No data found',
    INVALID_USER: 'Invalid User',
    USER_REGISTER_SUCCESS: 'Registered Successfully',
    USER_REGISTER_FAILURE: 'Unable to register at this time',
    UNABEL_TO_ADD_GALLERY: 'Unable to add gallery',
    THUMBNAIL_ERROR: 'Error while creating thumbnail',
    STATUS_UPDATE_SUCCESS: 'Status updated successfully',
    STATUS_UPDATE_FAILURE: 'Unable to update stauts. Try Again!',
    IMAGE_NOT_SELECTED: 'Image not selected',
    PROFILE_VERIFICATION_ADDED_SUCCESS: 'Profile verification images submitted successfully',
    PROFILE_VERIFICATION_ADDED_FAILURE: 'Unable to submit profile verification images at this moment',
    INVALID_TYPE: 'Invalid verification type (use : profile / driving_license/background)',
    VERIFIED_SUCCESS: 'Verified Successfully',
    DECLINED_SUCCESS: 'Declined Successfully',
    VERIFIED_FAILURE: 'Unable to verify. Try Again!',
    INTERESTED_IN_UPDATE_SUCCESS: 'InterestedIn updated successfully',
    INTERESTED_IN_UPDATE_FAILURE: 'Unable to update InterestedIn. Try Again!',
    CONNECTION_TYPE_UPDATE_SUCCESS: 'Connection Type updated successfully',
    CONNECTION_TYPE_UPDATE_FAILURE: 'Unable to update connection type. Try Again!',
    INTERESTS_UPDATE_SUCCESS: 'Interest updated succesfully',
    INTERESTS_UPDATE_FAILURE: 'Unable to update interest at this moment',
    LOCATION_UPDATE_SUCCESS: 'Location updated successfully',
    LOCATION_UPDATE_FAILURE: 'Unable to update location.Try Again!',
    NOTIFICATION_STATUS_UPDATE_SUCCESS: 'Notification status updated successfully',
    NOTIFICATION_STATUS_UPDATE_FAILURE: 'Unable to update notification status.Try Again!',
    NOTIFICATION_SENT_SUCCESS: 'Notification sent success',
    NOTIFICATION_SENT_FAILURE: 'Unable to send notification.Try Again!',
    OTP_EXPIRED_SUCCESS: 'OTP expired successfully!',
    OTP_EXPIRED_FAILURE: 'Unable to expire otp.Try Again!',
    EMAIL_ALREDY_EXIST: 'Account with this email already exist',
    SUBSCRIPTION_PURCHASED_SUCCESS: 'Subscription purchased successfully',
    SUBSCRIPTION_PURCHASED_FAILURE: 'Unable to subscribe',
    ACCOUNT_DELETE_SUCCESS: 'Account deleted successfully',
    ACCOUNT_DELETE_FAILURE: 'Unable to delete accout at this moment',
    MESSAGE_SENT_SUCCESS: 'Message sent successfully',
    MESSAGE_SENT_FAILURE: 'Unable to sent message. Try Again!',
}